[workspace]
resolver = "2"
members = [
    "srcms-server",
    "srcms-client",
    "srcms-data",
    "srcms-macros"
]

# For Zminimal-versions

# cargo +nightly update -Zminimal-versions
# cargo check
# cargo tree --target all -i [erroring package]

