[package]
name = "srcms-server"
version = "0.1.0"
edition = "2021"

[dependencies]

srcms-data = { path = "../data" }
srcms-macros = { path = "../macros" }

poem = "1.3.55"
shuttle-poem = "0.22.0"
shuttle-runtime = "0.22.0"
tokio = "1.26.0"
